import {readFileSync,writeFileSync} from 'node:fs';
const load=name=>readFileSync(new URL(name,import.meta.url),'utf8');
writeFileSync(new URL('pages.mjs',import.meta.url),`// Generated by build-pages.mjs; edit the HTML sources.\nexport const HTML=${JSON.stringify(load('index.html'))};\nexport const WORKBENCH=${JSON.stringify(load('workbench.html'))};\nexport const LANDING=${JSON.stringify(load('landing.html'))};\n`);
